### ISSUE TITLE
Minifier .error fatals the app

### ISSUE THREAD

**Issue by raiftekin** [dchest/jsmin#2]
Hey. https://github.com/dchest/jsmin/blob/master/jsmin.go#L65 (*minifier).error uses log.Fatal which fatals the app.

**Comment by Edw590** [comment]
I also have this problem. It's crashing the app. Could it be replaced with a log.Println() or similiar? Or I could make a PR with the change. It can't be crashing the app just because the JSON data isn't right.

**Comment by dchest** [comment]
Sorry, fixed in [f7b8dff](https://github.com/dchest/jsmin/commit/f7b8dfff241829494219e93e4ecf27901ca5d438).
